name: SpacePark Pipeline v1
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore Source/SpacePark.sln
      - name: Build
        run: dotnet build Source/SpacePark.sln

        